export const ADD_PATIENT = "ADD_PATIENT";
export const INCREMENT = "INCREMENT";

export const UPDATE_INAPPOINT = "UPDATE_INAPPOINT";
export const LOADING_INAPPOINT = "LOADING_INAPPOINT";
export const LOADING_FORM = "LOADING_FORM";
export const UPDATE_MSJ_SUCCESS = "UPDATE_MSJ_SUCCESS";
export const UPDATE_MSJ_ERROR = "UPDATE_MSJ_ERROR";

export const INAPPOINT_ERROR = "INAPPOINT_ERROR";

